Add automatic version handling
Energinet-DataHub/.github pull request #113
Opened 2022-06-22 15:26 UTC by CodeReaper

2022-06-23 06:57 UTC, Exobitt approved these changes
lgtm

2022-06-24 12:36 UTC, MartinSchmidt approved these changes

2022-06-24 12:44 UTC, MartinSchmidt requested changes

2022-06-24 12:44 UTC, MartinSchmidt commented on .github/actions/semver-add/action.yaml
> +        echo "::set-output name=result::${V_0}.${V_1}.${V_2}"
VERSION=1.2.3
MAJOR=0
MINOR=1
PATCH=0

Expected output:


echo "1.3.0"

2022-06-28 11:06 UTC, MartinSchmidt approved these changes

2022-06-28 11:19 UTC, merged