WIP: Split workflows by technology
Energinet-DataHub/.github pull request #152
Opened 2022-09-28 13:08 UTC by dstenroejl

2022-10-06 10:22 UTC, dstenroejl commented on .github/workflows/databricks-build-prerelease.yml
> +          filename: databricks.zip
Fixed

2022-10-07 07:35 UTC, Renetnielsen requested changes

2022-10-07 07:35 UTC, Renetnielsen commented on .github/workflows/ci-base.yml
> +      OPERATING_SYSTEM:
Why is this needed? We know ubuntu is the fastes and these jobs dont seem to be OS related, like building dotnet on windows since we code on windows.

2022-10-07 07:35 UTC, Renetnielsen commented on .github/workflows/infrastructure-build-prerelease.yml
> +      - name: Create prelease
Without knowing it, i think we maybe need to test this in Shared resources since its private repo.?
It SHOULD work in theory, but i can't say 100%.

2022-10-07 07:35 UTC, Renetnielsen commented on .github/workflows/python-ci-test-and-coverage.yml
> +      USE_NEW_ACTIONNAME:
Wouldnt it be better to just copy this job?
Using this parameter, you would then have to go back and remove it also from all the places where its been used = twice the workload, as just deprecating a workflow in .github.

2022-10-07 07:39 UTC, dstenroejl commented on .github/workflows/ci-base.yml
> +      OPERATING_SYSTEM:
To use the same technique as for e.g. "dotnet". It indicates we have a default value set to e.g. version 20.04 but in one repository we can easily test using 22.04

2022-10-07 08:12 UTC, Renetnielsen approved these changes

2022-10-07 08:18 UTC, merged