Support multiple emails when notifying teams
Energinet-DataHub/.github pull request #212
Opened 2023-02-24 09:38 UTC by dstenroejl

Update `notify-team.yml` workflow to be able to send notifications to multiple emails.

https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/942

2023-02-24 14:56 UTC, dstenroejl commented on .github/workflows/notify-team.yml
> +        uses: Energinet-DataHub/.github/.github/actions/send-email@xdast # TODO: Update ref to v10 when merged
Must update ref to correct version

2023-02-24 15:41 UTC, Renetnielsen requested changes
I think this should wait until #210 is merged.
After that, you will have to move the part you have in ci.yml into ci-base.yml

2023-02-27 08:44 UTC, djorgensendk commented on .github/workflows/ci.yml
> +      - main
Should we consider splitting this workflow into separate ci and cd workflows?

2023-02-27 08:44 UTC, djorgensendk commented on .github/workflows/notify-team.yml
> +        uses: Energinet-DataHub/.github/.github/actions/send-email@xdast # TODO: Update ref to v10 when merged
can we do this instead: ./.github/actions/send-email ?

2023-02-27 10:06 UTC, dstenroejl commented on .github/workflows/notify-team.yml
> +        uses: Energinet-DataHub/.github/.github/actions/send-email@xdast # TODO: Update ref to v10 when merged
I believe this would require the action to live in the repository where the workflow is called from. But I could be wrong.

2023-02-27 10:27 UTC, dstenroejl commented on .github/workflows/ci.yml
> +      - main
Not in this PR :)

2023-02-27 10:29 UTC, djorgensendk approved these changes

2023-02-27 10:29 UTC, Renetnielsen approved these changes

2023-02-27 10:29 UTC, merged