Publish test results
Energinet-DataHub/.github pull request #249
Opened 2023-03-28 12:34 UTC by kerbou

Publish test results after running testsuite

Reference: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/the-outlaws/997

2023-03-29 19:09 UTC, Renetnielsen requested changes
Many inputs are using UPPERCASE

2023-03-29 19:09 UTC, Renetnielsen commented on .github/workflows/dotnet-postbuild-test.yml
> +          comment_title: Test results for ${{ inputs.TESTS_DLL_FILE_PATH }}
Inputs are lowercase now

2023-03-30 08:25 UTC, kerbou commented on .github/workflows/dotnet-postbuild-test.yml
> +          check_name: Test results for ${{ inputs.TESTS_DLL_FILE_PATH }}
Fixed

2023-03-30 08:26 UTC, kerbou commented on .github/workflows/dotnet-postbuild-test.yml
> +          comment_title: Test results for ${{ inputs.TESTS_DLL_FILE_PATH }}
Fixed

2023-03-30 08:33 UTC, Renetnielsen approved these changes

2023-03-30 08:48 UTC, merged