Refactor Structurizr workflow
Energinet-DataHub/.github pull request #261
Opened 2023-05-09 12:56 UTC by dstenroejl

Refactor workflow:
- [x] Use environment variables to configure Structurizr Lite for loading the correct DSL file and any layouts in the JSON file. Doing so will enable support for `!include` with relative file path, and the use of manual layouts.
- [x] Only support the use of one primary DSL file, which can `!include` up to one other local DSL file. Doing so reduces complexity in the workflow, and makes it easier to correctly detect the changes that should render diagrams.
- [x] Update documentation in the workflow and the ReadMe.md file

Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1102

2023-05-09 14:25 UTC, Renetnielsen requested changes

2023-05-09 14:29 UTC, dstenroejl commented on .github/workflows/structurizr-render-diagrams.yml
> +    secrets:
> Would it make sense to just call this pat_token and make the description/documentation include the access scopes needed? Other places we do not call them pat_api_role_repo either. The example is of course exaggerated to make a point

I believe it was named like this because its the name of the secret and we use "inherit".

2023-05-09 14:35 UTC, dstenroejl commented on .github/workflows/structurizr-render-diagrams.yml
> +        id: diagrams-changed
We haven't mentioned this in our guidelines: https://energinet.atlassian.net/wiki/spaces/D3/pages/351469626/GitHub+Actions+Guidelines#GitHub-Actions-YAML-files

I will change it here, but there is plenty of places where we use kebab-case instead of snake_case for id's.

2023-05-09 15:08 UTC, Renetnielsen commented on .github/workflows/structurizr-render-diagrams.yml
> +    secrets:
Since this is not using 
```
 secrets:  inherit
```
From the calling workflow, but specifying the variable, this is parsed on as a value and is as to my knowledge not needed to be 1:1 mapping.

This make the value of the variable is up to the creator to decide, whereas my point about the input that goes into the variable is in my opinion not something the workflow should have any bias about.
So this could easily be named pat_token like for instance we do here:

https://github.com/Energinet-DataHub/.github/blob/main/.github/workflows/dispatch-deployment-request.yml#L37

2023-05-10 12:36 UTC, dstenroejl commented on .github/workflows/structurizr-render-diagrams.yml
> +    secrets:
I will rename the secret name so it hints of what it is used for, and refactor any calling workflows to set this explicit and not use 'inherit'.

2023-05-10 12:52 UTC, Renetnielsen approved these changes

2023-05-10 12:56 UTC, merged