Updated workflow to new flow
Energinet-DataHub/.github pull request #48
Opened 2022-02-15 08:09 UTC by MartinSchmidt

2022-02-15 08:24 UTC, Chrisbh approved these changes

2022-02-15 08:26 UTC, CodeReaper requested changes

2022-02-15 08:26 UTC, CodeReaper commented on .github/actions/get-semver/action.yaml
> +  Get semver from a path in a yaml file and if PR then append extra values.
There is no `if` statements nor is there any appending happening.

2022-02-15 08:26 UTC, CodeReaper commented on .github/workflows/version-increment-check.yaml
> +        if: ${{ steps.current_tag.outputs.result != steps.semvers.outputs.patch && steps.current_tag.outputs.result != steps.semvers.outputs.minor && steps.current_tag.outputs.result != steps.semvers
Comparing patch, minor and major against `steps.current_tag.outputs.result` seems incorrect.

2022-02-15 08:46 UTC, MartinSchmidt commented on .github/actions/get-semver/action.yaml
> +  Get semver from a path in a yaml file and if PR then append extra values.
if exists in line 57 in bash.

2022-02-15 08:53 UTC, MartinSchmidt commented on .github/workflows/version-increment-check.yaml
> +        if: ${{ steps.current_tag.outputs.result != steps.semvers.outputs.patch && steps.current_tag.outputs.result != steps.semvers.outputs.minor && steps.current_tag.outputs.result != steps.semvers
steps.current_tag.outputs.result is the output value from the yaml-get that returns the current value from the yaml file.

2022-02-15 08:58 UTC, CodeReaper approved these changes

2022-02-16 07:10 UTC, Renetnielsen approved these changes

2022-02-16 07:19 UTC, Renetnielsen approved these changes

2022-02-16 07:23 UTC, merged