Update version-increment-check.yaml
Energinet-DataHub/.github pull request #56
Opened 2022-02-24 09:27 UTC by RasmusGodske

Workflow can fail without stopping, which seems to be a bug as seen in the link below:

https://github.com/Energinet-DataHub/greenforce-frontend/runs/5316121408?check_suite_focus=true

2022-02-25 12:00 UTC, CodeReaper commented on .github/workflows/version-increment-check.yaml
> +        continue-on-error: false
Let's keep the continue-on-error as true and instead address the `if` statement in "Check versions" to ensure we get the error message below.

We currently have this:
```
      - name: Check versions
        if: ${{ steps.is_prev_tag_valid.outcome == 'success' && steps.current_tag.outputs.result != steps.semvers.outputs.patch && steps.current_tag.outputs.result != steps.semvers.outputs.minor && steps.current_tag.outputs.result != steps.semvers.outputs.major }}
```

We could update it to this:
```
      - name: Check versions
        if: ${{ steps.is_prev_tag_valid.outcome != 'success' || (steps.current_tag.outputs.result != steps.semvers.outputs.patch && steps.current_tag.outputs.result != steps.semvers.outputs.minor && steps.current_tag.outputs.result != steps.semvers.outputs.major) }}
```

2022-02-28 07:05 UTC, MartinSchmidt reviewed
I am not sure i understand, you changed the line to false, but the comment says otherwise.

What are the actual suggests of this PR?

2022-02-28 09:21 UTC, CodeReaper commented
@MartinSchmidt - I am assuming you thought I made the `true -> false` change. I did not. I am suggesting to revert that change and instead make the changes I proposed.

2022-02-28 14:05 UTC, MartinSchmidt requested changes
Read by review in line

2022-02-28 14:45 UTC, MartinSchmidt approved these changes

2022-02-28 14:46 UTC, merged